### ISSUE TITLE
Unexpected result.

### ISSUE THREAD

**Issue by shaneMangudi** [erasaur/session-helper#1]
``` handlebars
{{Session 'selectedItem' eq='firstItem' f='muted'}}
```

The above statement returns `true` instead of an empty string when `selectedItem` is equal to `firstItem`.

**Comment by shaneMangudi** [comment]
I sent a pull request. But I think I messed it up and isn't attached to this issue.

**Comment by shaneMangudi** [comment]
Could you also increment the version number and upload the new build to Atmosphere ?
It still downloads the old version when I do `meteor add erasaur:session-helper`

**Comment by erasaur** [comment]
Yep, sorry about that -- been quite busy recently. I'll go ahead and publish the new one now.
